<?php // -*-mode: PHP; coding:utf-8;-*-
// $Id: footer.inc 1781 2011-01-31 11:02:00Z cimorrison $

function print_theme_footer()
{
?>
  
  <script>
      $(document).foundation();
  </script>
  </div>
    <div style="background-color:#000000; clear:both; height:70px;">
	  <p style="color:#ccc; text-align:center; padding-top:20px">©2014 Colegio de Psicólogos Distrito VII. Todos los derechos reservados.</p>
    </div>
	
  </body>
</html>
<?php

}
 