<?php // -*-mode: PHP; coding:utf-8;-*-
// $Id: footer.inc 1781 2011-01-31 11:02:00Z cimorrison $

function print_theme_footer()
{
?>
  
  <script>
      $(document).foundation();
  </script>
  </div>
    <div style="background-color:#000000; clear:both; height:90px; min-width:480px;">
	  <p style="color:#ccc; text-align:center; padding-top:10px">Sistema de reserva de consultorios v.1.0 - ©2014 Colegio de Psicólogos Distrito VII. Todos los derechos reservados.</p>
	  <a href="contacto.php"><p style="color:#ccc; text-align:center; margin-top:-20px">Diseño y programación: Ciafardini, Martin - De la Penna, Manuel</p></a>
    </div>
	
  </body>
</html>
<?php

}
 